-- QO2 Supabase schema
-- Run this in: Supabase Dashboard -> SQL Editor -> New query.
-- Idempotent: safe to run multiple times (CREATE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).

-- ============================================================
-- public.users
-- Student profile, written by the legacy TUI flow (SaveUserInfo).
-- user_id is the UUID from Supabase Auth (anonymous sign-in).
-- ============================================================
create table if not exists public.users (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  name       text,
  email      text,
  phone      text,
  year       int,
  oscian     boolean not null default false,
  created_at timestamptz not null default now()
);

-- ============================================================
-- public.sessions
-- One row per TUI session (initializeSessionRow / updateSessionScore).
-- session_id is the numeric key the client upserts against.
-- ============================================================
create table if not exists public.sessions (
  session_id bigint generated by default as identity primary key,
  user_id    uuid references auth.users (id) on delete cascade,
  time       text,
  notes      text,
  score      int not null default 0,
  result     text,
  created_at timestamptz not null default now()
);

create index if not exists sessions_user_idx on public.sessions (user_id);

-- ============================================================
-- public.questions
-- Question bank for the legacy TUI flow (GenerateQuestionSet).
-- ============================================================
create table if not exists public.questions (
  question_id    bigint generated by default as identity primary key,
  text           text not null,
  topic          text,
  difficulty     int not null default 0,
  oneShot        boolean not null default false,
  test_script    text,
  setup_script   text,
  cleanup_script text,
  created_at     timestamptz not null default now()
);

-- ============================================================
-- public.submissions
-- Used by BOTH flows:
--   * CTF/CLI (active): qo start -> SendLeaderboardFlag inserts
--     {student_id, question_id, flag}. question_id holds the level
--     key, e.g. 'challenges/level1'. The leaderboard app reads these.
--   * Legacy TUI: SubmitQuestion inserts {session_id, question_id,
--     answer, score, result}.
-- Columns are nullable so both flows coexist in one table.
-- ============================================================
create table if not exists public.submissions (
  id          bigint generated by default as identity primary key,
  student_id  text,
  question_id text not null,
  flag        text,
  session_id  bigint,
  answer      text,
  score       int,
  result      text,
  created_at  timestamptz not null default now()
);

create index if not exists submissions_student_idx  on public.submissions (student_id);
create index if not exists submissions_question_idx on public.submissions (question_id);
create index if not exists submissions_session_idx on public.submissions (session_id);
create index if not exists submissions_created_idx on public.submissions (created_at desc);

-- Make sure the columns the CTF/leaderboard path needs exist, even if the
-- table predates this script.
alter table public.submissions add column if not exists student_id text;
alter table public.submissions add column if not exists flag text;
alter table public.submissions add column if not exists created_at timestamptz not null default now();

-- ============================================================
-- public.test_submissions
-- Dry-run table: the instructor sends students a TEST archive
-- (test.enc). When a student passes a test level (level key like
-- 'test1'..'test10'), qo2 records the row here instead of in
-- 'submissions', so the team can confirm the whole submission
-- pipeline works before the real event.
-- ============================================================
create table if not exists public.test_submissions (
  id          bigint generated by default as identity primary key,
  student_id  text not null,
  question_id text not null,
  flag        text,
  created_at  timestamptz not null default now()
);

create index if not exists test_submissions_student_idx  on public.test_submissions (student_id);
create index if not exists test_submissions_question_idx on public.test_submissions (question_id);
create index if not exists test_submissions_created_idx on public.test_submissions (created_at desc);

-- ============================================================
-- public.session_logs
-- "Who entered" attendance log. Every `qo start` records one row
-- here (best-effort, in the background) so the admin logs page can
-- show which roster students started a session and which didn't.
-- source = 'eval' | 'test' (from `qo start -m`).
-- ============================================================
create table if not exists public.session_logs (
  id         bigint generated by default as identity primary key,
  student_id text not null,
  source     text not null default 'eval',
  entered_at timestamptz not null default now()
);

create index if not exists session_logs_student_idx on public.session_logs (student_id);
create index if not exists session_logs_source_idx  on public.session_logs (source);

-- ============================================================
-- RLS
-- The qo2 CLI/TUI write via the service role (bypasses RLS) and the
-- leaderboard reads via the service role server-side, so no policies are
-- required. Enabling RLS is still good hygiene; uncomment if you want
-- browser access with the anon key (not needed for this app).
-- ============================================================
alter table public.users       enable row level security;
alter table public.sessions    enable row level security;
alter table public.questions   enable row level security;
alter table public.submissions enable row level security;
alter table public.test_submissions enable row level security;
alter table public.session_logs enable row level security;

-- The sandbox authenticates with the publishable (anon) key, so the anon role
-- may INSERT completions and session entries. No SELECT policy exists: only the
-- service-role key (used by the leaderboard app server-side) can read these.
create policy "sandbox inserts submissions"
  on public.submissions
  for insert
  to anon
  with check (true);

create policy "sandbox inserts test_submissions"
  on public.test_submissions
  for insert
  to anon
  with check (true);

create policy "sandbox inserts session_logs"
  on public.session_logs
  for insert
  to anon
  with check (true);

-- Uncomment to allow public reads (NOT recommended — flags are sensitive):
-- create policy "anon read submissions" on public.submissions for select to anon using (true);